development:
  password: 
  theme_id: ""
  store: 
  asset_url: "//cdn.shopify.com/s/files/0/0000/0000/t/0/assets/"
  views:
  - config
  - layout
  - locales
  - sections
  - snippets
  - templates
  dist: assets/
  scripts:
  - src/scripts/*.js
  - src/scripts/**/*.js
  - src/scripts/**/**/*.js
  scriptsToLint:
  - src/scripts/*.js
  - src/scripts/**/*.js
  - src/scripts/**/**/*.js
  - src/scripts/**/**/**/*.js
  - "!src/scripts/libs/**"
  sassIndex:
  - src/styles/index.scss
  sassFilesToLint:
  - src/styles/**
  - "!src/styles/libs/**"

